package com.github.coderslabs.mobbuckets.extra;

import net.minecraft.entity.EntityType;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;

public class ItemList {
    public static Item bucket_of_bat;
    public static Item bucket_of_bee;
    public static Item bucket_of_blaze;
    public static Item bucket_of_cat;
    public static Item bucket_of_cave_spider;
    public static Item bucket_of_chicken;
    public static Item bucket_of_cow;
    public static Item bucket_of_creeper;
    public static Item bucket_of_dolphin;
    public static Item bucket_of_donkey;
    public static Item bucket_of_drowned;
    public static Item bucket_of_elder_guardian;
    public static Item bucket_of_enderman;
    public static Item bucket_of_endermite;
    public static Item bucket_of_evoker;
    public static Item bucket_of_fox;
    public static Item bucket_of_ghast;
    public static Item bucket_of_giant;
    public static Item bucket_of_guardian;
    public static Item bucket_of_hoglin;
    public static Item bucket_of_horse;
    public static Item bucket_of_husk;
    public static Item bucket_of_illusioner;
    public static Item bucket_of_iron_golem;
    public static Item bucket_of_magma_cube;
    public static Item bucket_of_mooshroom;
    public static Item bucket_of_ocelot;
    public static Item bucket_of_panda;
    public static Item bucket_of_parrot;
    public static Item bucket_of_phantom;
    public static Item bucket_of_pig;
    public static Item bucket_of_piglin;
    public static Item bucket_of_pillager;
    public static Item bucket_of_polar_bear;
    public static Item bucket_of_rabbit;
    public static Item bucket_of_ravager;
    public static Item bucket_of_sheep;
    public static Item bucket_of_shulker;
    public static Item bucket_of_silverfish;
    public static Item bucket_of_snow_golem;
    public static Item bucket_of_skeleton;
    public static Item bucket_of_slime;
    public static Item bucket_of_spider;
    public static Item bucket_of_stray;
    public static Item bucket_of_strider;
    public static Item bucket_of_squid;
    public static Item bucket_of_turtle;
    public static Item bucket_of_vindicator;
    public static Item bucket_of_vex;
    public static Item bucket_of_witch;
    public static Item bucket_of_wither_skeleton;
    public static Item bucket_of_wolf;
    public static Item bucket_of_zoglin;
    public static Item bucket_of_zombie;
    public static Item bucket_of_zombie_villager;
    public static Item bucket_of_zombified_piglin;
    public static Item bucket_of_trader_llama;
    public static Item bucket_of_llama;
    public static Item bucket_of_mule;
    public static Item bucket_of_ender_dragon;
    public static Item bucket_of_wither;
    public static Item bucket_of_skeleton_horse;
    public static Item bucket_of_zombie_horse;
    public static Item bucket_of_villager;
    public static Item bucket_of_wandering_trader;
    public static Item bucket_of_entity;

    public ItemList() {
    }

    static {
        bucket_of_bat = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.BAT);
        bucket_of_bee = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.BEE);
        bucket_of_blaze = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.BLAZE);
        bucket_of_cat = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.CAT);
        bucket_of_cave_spider = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.CAVE_SPIDER);
        bucket_of_chicken = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.CHICKEN);
        bucket_of_cow = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.COW);
        bucket_of_creeper = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.CREEPER);
        bucket_of_dolphin = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.DOLPHIN);
        bucket_of_donkey = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.DONKEY);
        bucket_of_drowned = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.DROWNED);
        bucket_of_elder_guardian = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ELDER_GUARDIAN);
        bucket_of_enderman = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ENDERMAN);
        bucket_of_endermite = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ENDERMITE);
        bucket_of_evoker = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.EVOKER);
        bucket_of_fox = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.FOX);
        bucket_of_ghast = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.GHAST);
        bucket_of_giant = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.GIANT);
        bucket_of_guardian = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.GUARDIAN);
        bucket_of_hoglin = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.HOGLIN);
        bucket_of_horse = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.HORSE);
        bucket_of_husk = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.HUSK);
        bucket_of_illusioner = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ILLUSIONER);
        bucket_of_iron_golem = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.IRON_GOLEM);
        bucket_of_magma_cube = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.MAGMA_CUBE);
        bucket_of_mooshroom = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.MOOSHROOM);
        bucket_of_ocelot = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.OCELOT);
        bucket_of_panda = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PANDA);
        bucket_of_parrot = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PARROT);
        bucket_of_phantom = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PHANTOM);
        bucket_of_pig = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PIG);
        bucket_of_piglin = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PIGLIN);
        bucket_of_pillager = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.PILLAGER);
        bucket_of_polar_bear = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.POLAR_BEAR);
        bucket_of_rabbit = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.RABBIT);
        bucket_of_ravager = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.RAVAGER);
        bucket_of_sheep = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SHEEP);
        bucket_of_shulker = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SHULKER);
        bucket_of_silverfish = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SILVERFISH);
        bucket_of_snow_golem = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SNOW_GOLEM);
        bucket_of_skeleton = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SKELETON);
        bucket_of_slime = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SLIME);
        bucket_of_spider = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SPIDER);
        bucket_of_stray = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.STRAY);
        bucket_of_strider = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.STRIDER);
        bucket_of_squid = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SQUID);
        bucket_of_turtle = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.TURTLE);
        bucket_of_vindicator = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.VINDICATOR);
        bucket_of_vex = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.VEX);
        bucket_of_witch = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.WITCH);
        bucket_of_wither_skeleton = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.WITHER_SKELETON);
        bucket_of_wolf = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.WOLF);
        bucket_of_zoglin = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ZOGLIN);
        bucket_of_zombie = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ZOMBIE);
        bucket_of_zombie_villager = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ZOMBIE_VILLAGER);
        bucket_of_zombified_piglin = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ZOMBIFIED_PIGLIN);
        bucket_of_trader_llama = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.TRADER_LLAMA);
        bucket_of_llama = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.LLAMA);
        bucket_of_mule = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.MULE);
        bucket_of_ender_dragon = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ENDER_DRAGON);
        bucket_of_wither = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.WITHER);
        bucket_of_skeleton_horse = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.SKELETON_HORSE);
        bucket_of_zombie_horse = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.ZOMBIE_HORSE);
        bucket_of_villager = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.VILLAGER);
        bucket_of_wandering_trader = new BucketOfVanillaEntityItem((new Item.Settings().group(ItemGroup.MISC)), EntityType.WANDERING_TRADER);
        bucket_of_entity = new BucketOfEntityItem((new Item.Settings().group(ItemGroup.MISC)));
    }
}