package com.github.coderslabs.mobbuckets.init;

import com.github.coderslabs.mobbuckets.item.*;
import com.github.evoslab.cookiecore.datagen.MainGenerator;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.passive.BatEntity;
import net.minecraft.entity.passive.BeeEntity;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import static com.github.coderslabs.mobbuckets.MobBuckets.*;

public class MobBucketItems {
    private static final MainGenerator generator = new MainGenerator(MOD_ID);

    public static AnimalBucketItem BAT_BUCKET_ITEM;
    public static AnimalBucketItem BEE_BUCKET_ITEM;
    public static AnimalBucketItem BLAZE_BUCKET_BUCKET_ITEM;
    public static AnimalBucketItem CAT_BUCKET_ITEM;
    public static AnimalBucketItem CAVE_SPIDER_BUCKET_ITEM;
    public static AnimalBucketItem CHICKEN_BUCKET_ITEM;
    public static AnimalBucketItem COW_BUCKET_ITEM;
    public static AnimalBucketItem CREEPER_BUCKET_ITEM;
    public static AnimalBucketItem DOLPHIN_BUCKET_ITEM;
    public static AnimalBucketItem DONKEY_BUCKET_ITEM;
    public static AnimalBucketItem DROWNED_BUCKET_ITEM;
    public static AnimalBucketItem ELDER_GUARDIAN_BUCKET_ITEM;
    public static EnderDragonBucketItem ENDER_DRAGON_BUCKET_ITEM;
    public static AnimalBucketItem ENDERMAN_BUCKET_ITEM;
    public static AnimalBucketItem ENDERMITE_BUCKET_ITEM;
    public static AnimalBucketItem EVOKER_BUCKET_ITEM;
    public static AnimalBucketItem FOX_BUCKET_ITEM;
    public static AnimalBucketItem GHAST_BUCKET_ITEM;
    public static AnimalBucketItem GUARDIAN_BUCKET_ITEM;
    public static AnimalBucketItem HOGLIN_BUCKET_ITEM;
    public static AnimalBucketItem HORSE_BUCKET_ITEM;
    public static AnimalBucketItem HUSK_BUCKET_ITEM;
    public static AnimalBucketItem IRON_GOLEM_BUCKET_ITEM;
    public static AnimalBucketItem LLAMA_BUCKET_ITEM;
    public static AnimalBucketItem MAGMA_CUBE_BUCKET_ITEM;
    public static AnimalBucketItem RED_MOOSHROOM_BUCKET_ITEM;
    public static AnimalBucketItem BROWN_MOOSHROOM_BUCKET_ITEM;
    public static AnimalBucketItem MULE_BUCKET_ITEM;
    public static AnimalBucketItem OCELOT_BUCKET_ITEM;
    public static AnimalBucketItem PANDA_BUCKET_ITEM;
    public static AnimalBucketItem PARROT_BUCKET_ITEM;
    public static AnimalBucketItem PHANTOM_BUCKET_ITEM;
    public static AnimalBucketItem PIG_BUCKET_ITEM;
    public static AnimalBucketItem PIGLIN_BRUTE_BUCKET_ITEM;
    public static AnimalBucketItem PIGLIN_BUCKET_ITEM;
    public static AnimalBucketItem PILLAGER_BUCKET_ITEM;
    public static AnimalBucketItem POLAR_BEAR_BUCKET_ITEM;
    public static AnimalBucketItem RABBIT_BUCKET_ITEM;
    public static AnimalBucketItem RAVAGER_BUCKET_ITEM;
    public static AnimalBucketItem SHEEP_BUCKET_ITEM;
    public static AnimalBucketItem SHULKER_BUCKET_ITEM;
    public static AnimalBucketItem SKELETON_BUCKET_ITEM;
    public static AnimalBucketItem SKELETON_HORSE_BUCKET_ITEM;
    public static AnimalBucketItem SLIME_BUCKET_ITEM;
    public static AnimalBucketItem SNOW_GOLEM_BUCKET_ITEM;
    public static AnimalBucketItem SQUID_BUCKET_ITEM;
    public static AnimalBucketItem STRAY_BUCKET_ITEM;
    public static AnimalBucketItem COLD_STRIDER_BUCKET_ITEM;
    public static AnimalBucketItem WARM_STRIDER_BUCKET_ITEM;
    public static AnimalBucketItem TURTLE_BUCKET_ITEM;
    public static AnimalBucketItem VEX_BUCKET_ITEM;
    public static AnimalBucketItem VIlLAGER_BUCKET_ITEM;
    public static AnimalBucketItem VINDICATOR_BUCKET_ITEM;
    public static AnimalBucketItem WANDERING_TRADER_BUCKET_ITEM;
    public static AnimalBucketItem WITCH_BUCKET_ITEM;
    public static AnimalBucketItem WITHER_SKELETON_BUCKET_ITEM;
    public static AnimalBucketItem WOLF_BUCKET_BUCKET_ITEM;
    public static AnimalBucketItem ZOGLIN_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIE_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIE_VILLAGER_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIFIED_PIGLIN_BUCKET_ITEM;

    public static void init(){
        BAT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BAT, Fluids.EMPTY, Properties.MOB_BUCKET, "", BAT_BUCKET_ITEM), "bat_bucket");
        BEE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BEE, Fluids.EMPTY, Properties.MOB_BUCKET, "", BEE_BUCKET_ITEM), "bee_bucket");
        BLAZE_BUCKET_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BLAZE, Fluids.EMPTY, Properties.MOB_BUCKET, "", BLAZE_BUCKET_BUCKET_ITEM), "blaze_bucket");
        CAT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CAT, Fluids.EMPTY, Properties.MOB_BUCKET, "", CAT_BUCKET_ITEM), "cat_bucket");
        CAVE_SPIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CAVE_SPIDER, Fluids.EMPTY, Properties.MOB_BUCKET, "", CAVE_SPIDER_BUCKET_ITEM), "cave_spider_bucket");
        CHICKEN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CHICKEN, Fluids.EMPTY, Properties.MOB_BUCKET, "", CHICKEN_BUCKET_ITEM), "chicken_bucket");
        COW_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.COW, Fluids.EMPTY, Properties.MOB_BUCKET, "", COW_BUCKET_ITEM), "cow_bucket");
        CREEPER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CREEPER, Fluids.EMPTY, Properties.MOB_BUCKET, "", CREEPER_BUCKET_ITEM), "creeper_bucket");
        DOLPHIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DOLPHIN, Fluids.EMPTY, Properties.MOB_BUCKET, "", DOLPHIN_BUCKET_ITEM), "dolphin_bucket");
        DONKEY_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DONKEY, Fluids.EMPTY, Properties.MOB_BUCKET, "", DONKEY_BUCKET_ITEM), "donkey_bucket");
        DROWNED_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DROWNED, Fluids.WATER, Properties.MOB_BUCKET, "", DROWNED_BUCKET_ITEM), "drowned_bucket");
        ELDER_GUARDIAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ELDER_GUARDIAN, Fluids.WATER, Properties.MOB_BUCKET, "", ELDER_GUARDIAN_BUCKET_ITEM), "elder_guardian_bucket");
        ENDER_DRAGON_BUCKET_ITEM  = generator.item.registerBlandItem(new EnderDragonBucketItem(Properties.MOB_BUCKET, ENDER_DRAGON_BUCKET_ITEMSTACK), "ender_dragon_bucket");
        ENDERMAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ENDERMAN, Fluids.EMPTY, Properties.MOB_BUCKET, "", ENDERMAN_BUCKET_ITEM), "enderman_bucket");
        ENDERMITE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ENDERMITE, Fluids.EMPTY, Properties.MOB_BUCKET, "", ENDERMITE_BUCKET_ITEM), "endermite_bucket");
        EVOKER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.EVOKER, Fluids.EMPTY, Properties.MOB_BUCKET, "", EVOKER_BUCKET_ITEM), "evoker_bucket");
        FOX_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.FOX, Fluids.EMPTY, Properties.MOB_BUCKET, "", FOX_BUCKET_ITEM), "fox_bucket");
        GHAST_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.GHAST, Fluids.EMPTY, Properties.MOB_BUCKET, "", GHAST_BUCKET_ITEM), "ghast_bucket");
        GUARDIAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.GUARDIAN, Fluids.WATER, Properties.MOB_BUCKET, "", GUARDIAN_BUCKET_ITEM), "guardian_bucket");
        HOGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HOGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, "", HOGLIN_BUCKET_ITEM), "hoglin_bucket");
        HORSE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HORSE, Fluids.EMPTY, Properties.MOB_BUCKET, "", HORSE_BUCKET_ITEM), "horse_bucket");
        HUSK_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HUSK, Fluids.EMPTY, Properties.MOB_BUCKET, "", HUSK_BUCKET_ITEM), "husk_bucket");
        IRON_GOLEM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.IRON_GOLEM, Fluids.EMPTY, Properties.MOB_BUCKET, "", IRON_GOLEM_BUCKET_ITEM), "iron_golem_bucket");
        LLAMA_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.LLAMA, Fluids.EMPTY, Properties.MOB_BUCKET, "", LLAMA_BUCKET_ITEM), "llama_bucket");
        MAGMA_CUBE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MAGMA_CUBE, Fluids.LAVA, Properties.MOB_BUCKET, "", MAGMA_CUBE_BUCKET_ITEM), "magma_cube_bucket");
        RED_MOOSHROOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MOOSHROOM, Fluids.EMPTY, Properties.MOB_BUCKET, "", RED_MOOSHROOM_BUCKET_ITEM), "red_mooshroom_bucket");
        BROWN_MOOSHROOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MOOSHROOM, Fluids.EMPTY, Properties.MOB_BUCKET, "", BROWN_MOOSHROOM_BUCKET_ITEM), "brown_mooshroom_bucket");
        MULE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MULE, Fluids.EMPTY, Properties.MOB_BUCKET, "", MULE_BUCKET_ITEM), "mule_bucket");
        OCELOT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.OCELOT, Fluids.EMPTY, Properties.MOB_BUCKET, "", OCELOT_BUCKET_ITEM), "ocelot_bucket");
        PANDA_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PANDA, Fluids.EMPTY, Properties.MOB_BUCKET, "", PANDA_BUCKET_ITEM), "panda_bucket");
        PARROT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PARROT, Fluids.EMPTY, Properties.MOB_BUCKET, "", PARROT_BUCKET_ITEM), "parrot_bucket");
        PHANTOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PHANTOM, Fluids.EMPTY, Properties.MOB_BUCKET, "", PHANTOM_BUCKET_ITEM), "phantom_bucket");
        PIG_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIG, Fluids.EMPTY, Properties.MOB_BUCKET, "", PIG_BUCKET_ITEM), "pig_bucket");
        PIGLIN_BRUTE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIGLIN_BRUTE, Fluids.EMPTY, Properties.MOB_BUCKET, "", PIGLIN_BRUTE_BUCKET_ITEM), "piglin_brute_bucket");
        PIGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, "", PIGLIN_BUCKET_ITEM), "piglin_bucket");
        PILLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, "", PILLAGER_BUCKET_ITEM), "pillager_bucket");
        POLAR_BEAR_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.POLAR_BEAR, Fluids.EMPTY, Properties.MOB_BUCKET, "", POLAR_BEAR_BUCKET_ITEM), "polar_bear_bucket");
        RABBIT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.RABBIT, Fluids.EMPTY, Properties.MOB_BUCKET, "", RABBIT_BUCKET_ITEM), "rabbit_bucket");
        RAVAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.RAVAGER, Fluids.EMPTY, Properties.MOB_BUCKET, "", RAVAGER_BUCKET_ITEM), "ravager_bucket");
        SHEEP_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SHEEP, Fluids.EMPTY, Properties.MOB_BUCKET, "", SHEEP_BUCKET_ITEM), "sheep_bucket");
        SHULKER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SHULKER, Fluids.EMPTY, Properties.MOB_BUCKET, "", SHULKER_BUCKET_ITEM), "shulker_bucket");
        SKELETON_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SKELETON, Fluids.EMPTY, Properties.MOB_BUCKET, "", SKELETON_BUCKET_ITEM), "skeleton_bucket");
        SKELETON_HORSE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SKELETON_HORSE, Fluids.EMPTY, Properties.MOB_BUCKET, "", SKELETON_HORSE_BUCKET_ITEM), "skeleton_horse_bucket");
        SLIME_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SLIME, Fluids.EMPTY, Properties.MOB_BUCKET, "", SLIME_BUCKET_ITEM), "slime_bucket");
        SNOW_GOLEM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SNOW_GOLEM, Fluids.EMPTY, Properties.MOB_BUCKET, "", SNOW_GOLEM_BUCKET_ITEM), "snow_golem_bucket");
        SQUID_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SQUID, Fluids.EMPTY, Properties.MOB_BUCKET, "", SQUID_BUCKET_ITEM), "squid_bucket");
        STRAY_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRAY, Fluids.EMPTY, Properties.MOB_BUCKET, "", STRAY_BUCKET_ITEM), "stray_bucket");
        //COLD_STRIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRIDER, Fluids.EMPTY, Properties.MOB_BUCKET, "", COLD_STRIDER_BUCKET_ITE), "cold_strider_bucket");
        WARM_STRIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRIDER, Fluids.LAVA, Properties.MOB_BUCKET, "", WARM_STRIDER_BUCKET_ITEM), "warm_strider_bucket");
        TURTLE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.TURTLE, Fluids.EMPTY, Properties.MOB_BUCKET, "", TURTLE_BUCKET_ITEM), "turtle_bucket");
        VEX_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VEX, Fluids.EMPTY, Properties.MOB_BUCKET, "", VEX_BUCKET_ITEM), "vex_bucket");
        VIlLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, "", VIlLAGER_BUCKET_ITEM), "villager_bucket");
        VINDICATOR_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VINDICATOR, Fluids.EMPTY, Properties.MOB_BUCKET, "", VINDICATOR_BUCKET_ITEM), "vindicator_bucket");
        WANDERING_TRADER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WANDERING_TRADER, Fluids.EMPTY, Properties.MOB_BUCKET, "", WANDERING_TRADER_BUCKET_ITEM), "wandering_trader_bucket");
        WITCH_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WITCH, Fluids.EMPTY, Properties.MOB_BUCKET, "", WITCH_BUCKET_ITEM), "witch_bucket");
        WITHER_SKELETON_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WITHER_SKELETON, Fluids.EMPTY, Properties.MOB_BUCKET, "", WITHER_SKELETON_BUCKET_ITEM), "wither_skeleton_bucket");
        WOLF_BUCKET_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WOLF, Fluids.EMPTY, Properties.MOB_BUCKET, "", WOLF_BUCKET_BUCKET_ITEM), "wolf_bucket");
        ZOGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, "", ZOGLIN_BUCKET_ITEM), "zoglin_bucket");
        ZOMBIE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIE, Fluids.EMPTY, Properties.MOB_BUCKET, "", ZOMBIE_BUCKET_ITEM), "zombie_bucket");
        ZOMBIE_VILLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIE_VILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, "", ZOMBIE_VILLAGER_BUCKET_ITEM), "zombie_villager_bucket");
        ZOMBIFIED_PIGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIFIED_PIGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, "", ZOMBIFIED_PIGLIN_BUCKET_ITEM), "zombified_piglin_bucket");
    }

    public static ItemStack ENDER_DRAGON_BUCKET_ITEMSTACK = new ItemStack(ENDER_DRAGON_BUCKET_ITEM);

    public static class Properties {
        public static final Item.Settings MOB_BUCKET = new Item.Settings().maxCount(1).group(MOB_BUCKETS_TAB);
    }
}