package com.github.coderslabs.mobbuckets.init;

import com.github.coderslabs.mobbuckets.item.*;
import com.github.evoslab.cookiecore.datagen.MainGenerator;
import net.minecraft.entity.EntityType;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import static com.github.coderslabs.mobbuckets.MobBuckets.*;

public class MobBucketItems {
    private static final MainGenerator generator = new MainGenerator(MOD_ID);

    public static AnimalBucketItem BAT_BUCKET_ITEM;
    public static AnimalBucketItem BEE_BUCKET_ITEM;
    public static AnimalBucketItem BLAZE_BUCKET_BUCKET_ITEM;
    public static AnimalBucketItem CAT_BUCKET_ITEM;
    public static AnimalBucketItem CAVE_SPIDER_BUCKET_ITEM;
    public static AnimalBucketItem CHICKEN_BUCKET_ITEM;
    public static AnimalBucketItem COW_BUCKET_ITEM;
    public static AnimalBucketItem CREEPER_BUCKET_ITEM;
    public static AnimalBucketItem DOLPHIN_BUCKET_ITEM;
    public static AnimalBucketItem DONKEY_BUCKET_ITEM;
    public static AnimalBucketItem DROWNED_BUCKET_ITEM;
    public static AnimalBucketItem ELDER_GUARDIAN_BUCKET_ITEM;
    public static EnderDragonBucketItem ENDER_DRAGON_BUCKET_ITEM;
    public static AnimalBucketItem ENDERMAN_BUCKET_ITEM;
    public static AnimalBucketItem ENDERMITE_BUCKET_ITEM;
    public static AnimalBucketItem EVOKER_BUCKET_ITEM;
    public static AnimalBucketItem FOX_BUCKET_ITEM;
    public static AnimalBucketItem GHAST_BUCKET_ITEM;
    public static AnimalBucketItem GUARDIAN_BUCKET_ITEM;
    public static AnimalBucketItem HOGLIN_BUCKET_ITEM;
    public static AnimalBucketItem HORSE_BUCKET_ITEM;
    public static AnimalBucketItem HUSK_BUCKET_ITEM;
    public static AnimalBucketItem IRON_GOLEM_BUCKET_ITEM;
    public static AnimalBucketItem LLAMA_BUCKET_ITEM;
    public static AnimalBucketItem MAGMA_CUBE_BUCKET_ITEM;
    public static AnimalBucketItem RED_MOOSHROOM_BUCKET_ITEM;
    public static AnimalBucketItem BROWN_MOOSHROOM_BUCKET_ITEM;
    public static AnimalBucketItem MULE_BUCKET_ITEM;
    public static AnimalBucketItem OCELOT_BUCKET_ITEM;
    public static AnimalBucketItem PANDA_BUCKET_ITEM;
    public static AnimalBucketItem PARROT_BUCKET_ITEM;
    public static AnimalBucketItem PHANTOM_BUCKET_ITEM;
    public static AnimalBucketItem PIG_BUCKET_ITEM;
    public static AnimalBucketItem PIGLIN_BRUTE_BUCKET_ITEM;
    public static AnimalBucketItem PIGLIN_BUCKET_ITEM;
    public static AnimalBucketItem PILLAGER_BUCKET_ITEM;
    public static AnimalBucketItem POLAR_BEAR_BUCKET_ITEM;
    public static AnimalBucketItem RABBIT_BUCKET_ITEM;
    public static AnimalBucketItem RAVAGER_BUCKET_ITEM;
    public static AnimalBucketItem SHEEP_BUCKET_ITEM;
    public static AnimalBucketItem SHULKER_BUCKET_ITEM;
    public static AnimalBucketItem SKELETON_BUCKET_ITEM;
    public static AnimalBucketItem SKELETON_HORSE_BUCKET_ITEM;
    public static AnimalBucketItem SLIME_BUCKET_ITEM;
    public static AnimalBucketItem SNOW_GOLEM_BUCKET_ITEM;
    public static AnimalBucketItem SQUID_BUCKET_ITEM;
    public static AnimalBucketItem STRAY_BUCKET_ITEM;
    public static AnimalBucketItem COLD_STRIDER_BUCKET_ITEM;
    public static AnimalBucketItem WARM_STRIDER_BUCKET_ITEM;
    public static AnimalBucketItem TURTLE_BUCKET_ITEM;
    public static AnimalBucketItem VEX_BUCKET_ITEM;
    public static AnimalBucketItem VIlLAGER_BUCKET_ITEM;
    public static AnimalBucketItem VINDICATOR_BUCKET_ITEM;
    public static AnimalBucketItem WANDERING_TRADER_BUCKET_ITEM;
    public static AnimalBucketItem WITCH_BUCKET_ITEM;
    public static AnimalBucketItem WITHER_SKELETON_BUCKET_ITEM;
    public static AnimalBucketItem WOLF_BUCKET_BUCKET_ITEM;
    public static AnimalBucketItem ZOGLIN_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIE_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIE_VILLAGER_BUCKET_ITEM;
    public static AnimalBucketItem ZOMBIFIED_PIGLIN_BUCKET_ITEM;

    public static void init(){
        BAT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BAT, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "bat_bucket");
        BEE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BEE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "bee_bucket");
        BLAZE_BUCKET_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.BLAZE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "blaze_bucket");
        CAT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CAT, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "cat_bucket");
        CAVE_SPIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CAVE_SPIDER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "cave_spider_bucket");
        CHICKEN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CHICKEN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "chicken_bucket");
        COW_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.COW, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "cow_bucket");
        CREEPER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.CREEPER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "creeper_bucket");
        DOLPHIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DOLPHIN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "dolphin_bucket");
        DONKEY_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DONKEY, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "donkey_bucket");
        DROWNED_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.DROWNED, Fluids.WATER, Properties.MOB_BUCKET, ""), "drowned_bucket");
        ELDER_GUARDIAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ELDER_GUARDIAN, Fluids.WATER, Properties.MOB_BUCKET, ""), "elder_guardian_bucket");
        ENDER_DRAGON_BUCKET_ITEM  = generator.item.registerBlandItem(new EnderDragonBucketItem(Properties.MOB_BUCKET, ENDER_DRAGON_BUCKET_ITEMSTACK), "ender_dragon_bucket");
        ENDERMAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ENDERMAN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "enderman_bucket");
        ENDERMITE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ENDERMITE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "endermite_bucket");
        EVOKER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.EVOKER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "evoker_bucket");
        FOX_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.FOX, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "fox_bucket");
        GHAST_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.GHAST, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "ghast_bucket");
        GUARDIAN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.GUARDIAN, Fluids.WATER, Properties.MOB_BUCKET, ""), "guardian_bucket");
        HOGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HOGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "hoglin_bucket");
        HORSE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HORSE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "horse_bucket");
        HUSK_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.HUSK, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "husk_bucket");
        IRON_GOLEM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.IRON_GOLEM, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "iron_golem_bucket");
        LLAMA_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.LLAMA, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "llama_bucket");
        MAGMA_CUBE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MAGMA_CUBE, Fluids.LAVA, Properties.MOB_BUCKET, ""), "magma_cube_bucket");
        RED_MOOSHROOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MOOSHROOM, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "red_mooshroom_bucket");
        BROWN_MOOSHROOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MOOSHROOM, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "brown_mooshroom_bucket");
        MULE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.MULE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "mule_bucket");
        OCELOT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.OCELOT, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "ocelot_bucket");
        PANDA_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PANDA, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "panda_bucket");
        PARROT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PARROT, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "parrot_bucket");
        PHANTOM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PHANTOM, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "phantom_bucket");
        PIG_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIG, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "pig_bucket");
        PIGLIN_BRUTE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIGLIN_BRUTE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "piglin_brute_bucket");
        PIGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PIGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "piglin_bucket");
        PILLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.PILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "pillager_bucket");
        POLAR_BEAR_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.POLAR_BEAR, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "polar_bear_bucket");
        RABBIT_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.RABBIT, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "rabbit_bucket");
        RAVAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.RAVAGER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "ravager_bucket");
        SHEEP_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SHEEP, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "sheep_bucket");
        SHULKER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SHULKER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "shulker_bucket");
        SKELETON_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SKELETON, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "skeleton_bucket");
        SKELETON_HORSE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SKELETON_HORSE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "skeleton_horse_bucket");
        SLIME_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SLIME, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "slime_bucket");
        SNOW_GOLEM_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SNOW_GOLEM, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "snow_golem_bucket");
        SQUID_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.SQUID, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "squid_bucket");
        STRAY_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRAY, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "stray_bucket");
        COLD_STRIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRIDER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "cold_strider_bucket");
        WARM_STRIDER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.STRIDER, Fluids.LAVA, Properties.MOB_BUCKET, ""), "warm_strider_bucket");
        TURTLE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.TURTLE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "turtle_bucket");
        VEX_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VEX, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "vex_bucket");
        VIlLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "villager_bucket");
        VINDICATOR_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.VINDICATOR, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "vindicator_bucket");
        WANDERING_TRADER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WANDERING_TRADER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "wandering_trader_bucket");
        WITCH_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WITCH, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "witch_bucket");
        WITHER_SKELETON_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WITHER_SKELETON, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "wither_skeleton_bucket");
        WOLF_BUCKET_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.WOLF, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "wolf_bucket");
        ZOGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "zoglin_bucket");
        ZOMBIE_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIE, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "zombie_bucket");
        ZOMBIE_VILLAGER_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIE_VILLAGER, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "zombie_villager_bucket");
        ZOMBIFIED_PIGLIN_BUCKET_ITEM  = generator.item.registerBlandItem(new AnimalBucketItem(EntityType.ZOMBIFIED_PIGLIN, Fluids.EMPTY, Properties.MOB_BUCKET, ""), "zombified_piglin_bucket");
    }

    public static ItemStack ENDER_DRAGON_BUCKET_ITEMSTACK = new ItemStack(ENDER_DRAGON_BUCKET_ITEM);

    public static class Properties {
        public static final Item.Settings MOB_BUCKET = new Item.Settings().maxCount(1).group(MOB_BUCKETS_TAB);
    }
}